[package]
name = "tui-launcher"
version = "0.1.0"
edition = "2024"
description = "A dmenu-style TUI workflow launcher for ordinary CLI plugins"
license = "MIT"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
libc = "0.2.189"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.150"
shell-words = "1.1.0"
jsonpath-rfc9535 = "0.1.1"
ratatui = "0.30.2"
toml = "1.1.0"
avt = "0.18.0"
unicode-width = "0.2.2"
ratatui-image = { version = "11.0.6", default-features = false, features = ["crossterm"] }
image = { version = "0.25.6", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp"] }
