[workflow]
api = 1
name = "sys"

[views.main]
engine = "picker"
companion = "preview"

[views.main.picker.items]
file = "scripts/items.py"

[views.preview]
engine = "capture"

[views.preview.query]
type = "object"
item = { type = "object", default = {} }

[views.preview.capture.output]
file = "scripts/preview.py"

[views.main.bindings]
"ctrl+p" = "preview"
enter = "run"

[commands.run]
label = "Run"
type = "navigate"
file = "scripts/command.py"

[views.confirm]
engine = "picker"
[views.confirm.query]
type = "object"
input = "action"
action = { type = "string", default = "" }

[views.confirm.picker]
show_input = false
show_left_prefix = false

[views.confirm.picker.items]
file = "scripts/confirm_items.py"

[views.confirm.bindings]
enter = "confirm_exec"

[commands.confirm_exec]
label = "Confirm"
type = "navigate"
file = "scripts/confirm_exec.py"

[views.output]
engine = "capture"

[views.output.capture.output]
file = "scripts/run.py"

[commands.preview]
label = "Toggle Preview"
type = "companion"
target = "preview"
args = { item = "$selection" }
