[workflow]
api = 1
name = "sys"
entrypoint = "main"

[views.main]

[views.main.engine]
type = "picker"

[views.main.engine.config]
preview_ratio = 0.4
preview_min_width = 24
preview_default_open = false

[views.main.engine.config.items]
producer = "script"
[views.main.engine.config.items.handler]
file = "scripts/items.py"

[views.main.engine.config.preview]
producer = "script"
[views.main.engine.config.preview.handler]
file = "scripts/preview.py"

[views.main.keymap]
enter = "run"

[commands.run]
label = "Run"
type = "navigate"
producer = "script"
[commands.run.handler]
file = "scripts/command.py"

[views.confirm]
[views.confirm.query]
type = "object"
input = "action"
action = { type = "string", default = "" }

[views.confirm.engine]
type = "picker"

[views.confirm.engine.config]
show_input = false
show_left_prefix = false

[views.confirm.engine.config.items]
producer = "script"
[views.confirm.engine.config.items.handler]
file = "scripts/confirm_items.py"

[views.confirm.keymap]
enter = "confirm_exec"

[commands.confirm_exec]
label = "Confirm"
type = "navigate"
producer = "script"
[commands.confirm_exec.handler]
file = "scripts/confirm_exec.py"

[views.output.engine]
type = "capture"

[views.output.engine.config.output]
producer = "script"
[views.output.engine.config.output.handler]
file = "scripts/run.py"
