default_view = "core:default"
dmenu_view = "core:dmenu"
command_view = "core:command"

[viewtypes.launcher.engine]
type = "launcher"

[viewtypes.launcher.engine.config]
items = "{{ runtime:view.current.items }}"
commands = "{{ runtime:view.current.command }}"

[viewtypes.capture.engine]
type = "capture"

[viewtypes.embedded.engine]
type = "embedded"
