default_view = "core:default"
command_view = "core:command"

[defaults.picker.bindings]
exit = ["ctrl+c", "ctrl+d"]
open_commands = ["ctrl+k"]
toggle_preview = ["ctrl+p"]
back = ["escape"]
select_previous = ["up"]
select_next = ["down"]
delete_backward = ["backspace"]
clear_input = ["ctrl+u"]
delete_word = ["ctrl+w"]
activate = ["enter"]
