[workflow]
api = 1
name = "dmenu"

[views.main]
engine = "picker"
cancel_exit_code = 1

[views.main.picker.items]
file = "scripts/items.sh"

[views.main.query]
type = "object"
input = "initial"
initial = { type = "string", default = "" }
index = { type = "boolean", default = false }
with-nth = { type = "string", nullable = true }
accept-nth = { type = "string", nullable = true }
match-nth = { type = "string", nullable = true }
nth-delimiter = { type = "string", nullable = true }

[views.main.bindings]
"escape" = "@engine:picker.exit"
enter = "accept"
"" = "copy"

[commands.accept]
label = "Accept"
type = "return"
file = "scripts/result.sh"

[commands.copy]
label = "Copy selection"
type = "return"
file = "scripts/result.sh"
